Making it working !
YunoHost-Apps/pterodactyl_ynh pull request #30
Opened 2020-06-20 09:37 UTC by Aeris1One

2020-06-23 01:05 UTC, yalh76 commented
Courage, j'avais commencé et au bout de quelques heures j'ai abandonné ^^

2021-03-06 00:28 UTC, yalh76 requested changes

2021-03-06 00:28 UTC, yalh76 commented on scripts/install
> +ynh_replace_string "__DB_PASS__"   "$db_pwd"     "$final_path/.env"
```suggestion
ynh_replace_string "__DB_PWD_"   "$db_pwd"     "$final_path/.env"
```

2021-03-06 00:28 UTC, yalh76 commented on scripts/install
> +ynh_replace_string "__DB_NAME__"   "$db_name"    "$final_path/.env"
You should use https://yunohost.org/fr/packaging_apps_helpers?q=%2Fpackaging_apps_helpers
`ynh_replace_string --match_string=match_string --replace_string=replace_string --target_file=target_file`

2021-03-06 00:28 UTC, yalh76 commented on scripts/install
> +ynh_package_install make gcc g++
You should add that in _common.sh, in `pkg_dependencies`

2021-03-06 00:29 UTC, yalh76 commented
!testme

2021-03-06 18:43 UTC, Aeris1One commented
By the power of systemd, I invoke The Great App CI to test this Pull Request!

2021-03-14 08:03 UTC, Aeris1One commented
!testme

2021-03-14 08:05 UTC, ericgaspar commented
!testme

2021-12-04 13:09 UTC, ericgaspar commented
!testme

2022-03-26 16:44 UTC, yalh76 commented
!testme

2022-03-27 11:47 UTC, ericgaspar commented
!testme

2022-04-13 19:17 UTC, Aeris1One commented
What about those two open PRs ? Should #35 be merged into this one ?

2022-05-07 05:36 UTC, imnotjack91 commented
i want to help but i dont have much experience with this app.
I am also a relatively new yunohost user but i want to contribute. 
This app is important to me and i would like to see it make it to stable. 
where can i begin helping?

2024-10-21 17:52 UTC, closed without merging